version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports: 
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev 
    volumes:
      - ./data:/opt/keycloak/data/h2