version: '3'

services:
  nodejs_app:
    image: node:latest
    container_name: ch2-backend
    restart: always
    ports:
      - "3000:3000"  
    volumes:
      - .:/app
    working_dir: /app
    env_file: ../.env
    command: bash -c "npm install && npm run start"